- apps/frontend/src/assets/css/utilities/grid-pattern.css
- apps/frontend/src/pages/auth/components/sign-in-form/styles.module.css
- apps/frontend/src/pages/home/home.tsx
- apps/frontend/src/pages/home/styles.module.css
This feature below has already been merged [here](https://github.com/BinaryStudioAcademy/bsa-2025-checkly/pull/59), but in this PR I suggest enhancing it a little - add opacity control for more flexible grid variations.
```css
section[data-section-variant="brand"] {
--grid-color: var(--color-brand-primary);
--grid-opacity: 0.5;
background-color: var(--color-card-blue);
}
```
> feat: enhance grid-pattern css util cy-60

- apps/frontend/src/assets/css/scaffolding.css
Hello!
In scaffolding.css, there's an incorrect css var value used to set body font-family.
```css
body {
...
font-family: var(--font-primary); // s/b --font-family-primary
...
}
```
> fix: update body font family cy-76

- apps/backend/src/libs/modules/server-application/base-server-application.ts
By default, the route protection plugin defines all routes as private unless a route is explicitly set to be public.
When creating a route, a developer can define it as public. However, in the case of the documentation generated by Swagger, this is not possible, which causes the plugin to treat all of these documentation routes as private as well.
Therefore, the plugin correctly identifies all documentation routes as private.
To solve this, I modified the getWhiteRoutes method, which is responsible for identifying if a route is public, to include the documentation's route pattern as public.
> fix: whitelist to allow public access to api documentation cy-80

- apps/frontend/src/assets/css/utilities/wrapper.css
- apps/frontend/src/assets/css/variables/spacing.css
- apps/frontend/src/pages/auth/components/sign-in-form/styles.module.css
Hi guys!
Suggestion is to remove redundant --space-gutter-* variables that are just duplicating --space-* values. My idea was to abstract them, but now I see that it doesn't provide much sense. 
Other Developers might use just --space-* values directly or update spacing.css to add new meaningful and semantic variables - like --nav-padding or --card-gap.
Before:
```css
:root {
--gutter: var(--space-xs);
--space-gutter-3xs: var(--space-3xs);
--space-gutter-2xs: var(--space-2xs);
--space-gutter-xs: var(--space-xs);
--space-gutter-s: var(--space-s);
--space-gutter-m: var(--space-m);
--space-gutter-l: var(--space-l);
--space-gutter-xl: var(--space-xl);
--space-gutter-2xl: var(--space-2xl);
--space-gutter-3xl: var(--space-3xl);
--space-gutter-m-3xl: var(--space-m-3xl);
--base-radius: …
```
> fix: remove redundant css values cy-84

- apps/frontend/src/assets/css/reset.css
- apps/frontend/src/assets/css/utilities/scrollbar-gutter.css
- apps/frontend/src/assets/css/utilities/utilities.css
Hello guys!
[Bug ticket link](https://github.com/orgs/BinaryStudioAcademy/projects/33/views/1?pane=issue&itemId=122210407&issue=BinaryStudioAcademy%7Cbsa-2025-checkly%7C88)
QA team has found a visual bug - with `scrollbar-gutter: stable` ([MDN reference](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter)), that reserves space for a scrollbar, it also creates an unwanted blank space even when content doesn't overflow. It doesn't look good on sign-in/sing-up pages.
Actions taken:
1. Removed `scrollbar-gutter: stable` from html.
2. Added scrollbar-gutter-stable utility class, that can be used in case this feature to prevent content shifting needs to be applied to a container, or whatever element a Developer is working with.
```css
.scrollbar-gutter-stable {
scrollbar-gutter: …
```
> fix: scrollbar gutter cy-88

- apps/frontend/src/pages/home/components/visual-layouts/styles.module.css
This PR resolves the clipping issue on the Design Templates cards.
- Adjusted parent container's overflow handling and spacing
- Ensured cards scale smoothly on hover without edges being cut off
Please review and let me know if any additional refinements are required.
https://github.com/user-attachments/assets/21a8031f-bea4-4bed-85b6-dc82a6d8d987
> fix: card edges clipping on hover cy-143

- apps/frontend/src/pages/home/components/feedbacks-section/styles.module.css
> fix: block margin overlaps with screen border in small resolution cy-149

- apps/frontend/src/pages/home/components/header/header.tsx
Update "Sign in" button state in header based on auth status.
Button now displays "Sign In" for not authenticated users and "Profile" for authenticated users.
Note: this will work fully only after merging PR for the protected route, as the authentication check depends on the auth slice, and the logic for fetching and storing the user in that slice is handled in protected route.
> fix: update button state in header cy-153

- apps/frontend/src/libs/components/button/button.tsx
- apps/frontend/src/libs/components/loader/loader.tsx
- apps/frontend/src/libs/components/protected-route/protected-route.tsx
- apps/frontend/src/modules/auth/slices/auth.slice.ts
- apps/frontend/src/pages/auth/auth.tsx
- apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
- apps/frontend/src/pages/auth/components/sign-up-form/sign-up-form.tsx
Thanks to Olena's comment, the next issues were resolved:
1. Loader is shown for every pending action in auth
2. Loader is not shown on register/login request
What was done:
- The _Loader_ was modified to easily call it from different places
- The _Button_ was modified to allow it to contain a _Loader_
- A flag was added to _Auth slices_ to show _Loader_ only when the page is getting ready
- _Auth_ checks the state status and passes it to the forms
> fix: Prevent Sign In/Sign Up from reloading when receiving an error on submit cy-181

- apps/frontend/src/libs/components/dashboard/dashboard.tsx
- apps/frontend/src/libs/components/dashboard/styles.module.css
- apps/frontend/src/pages/dashboard-wrapper-mock/components/plan/components/task/styles.module.css
- apps/frontend/src/pages/dashboard-wrapper-mock/components/plan/components/task/task.tsx
Adjusted the Dashboard and My Plan sections to stretch properly.
Result:
> fix: Dashboard and My Plan sections stretch to fill the browser cy-232

- packages/shared/src/modules/quiz/libs/enums/quiz-api-path.enum.ts
Thanks to @watchlar2000 we found a problem with wrong api path in the deployed version of Checkly which resulted in the infinite loading screen. Small fix is introduced in current PR which only changes ROOT path.
Tested locally
1. GET /quiz-questions
2. POST /quiz
> fix(frontend): fixed quiz api path cy-254

- apps/frontend/src/modules/auth/slices/actions.ts
According to Bruno, the logout button should take you to the homepage, not back to the login page.
> refactor(frontend): change logout navigation to homepage cy-169

- apps/frontend/src/libs/components/button/button.tsx
- apps/frontend/src/libs/components/decorative-image/decorative-image.tsx
- tsconfig.json
Hi!
TS Config has been updated to remove `"exactOptionalPropertyTypes": true`. Issue #273.
> feat: remove exact-optional-property-types from ts-config cy-273

- apps/frontend/src/libs/components/app-header/user-menu.tsx
Returned the buttons i deleted, since we don't want to see them only on Desktop version, while we want them to remain on tablets/mobiles. I just added a simple css class that was implemented before. It hides those for desktop version and only makes them appear on tablets/mobiles.
> fix(frontend): return dropdown buttons for tablets/phones cy-304

- apps/frontend/src/pages/quiz/questions/components/notes-page/notes-page.tsx
One small fix was needed. Notes page didn't allow spaces (blanks) when typing the text. It was implemented before, but I forgot to add it to the notes page too.
> fix(frontend): notes page sanitizer cy-15

- apps/frontend/src/libs/components/plan-styles/plan-style/styles.module.css
- apps/frontend/src/pages/dashboard-wrapper-mock/components/plan/plan.tsx
- apps/frontend/src/pages/dashboard-wrapper-mock/components/plan/styles.module.css
- apps/frontend/src/pages/plan-style-overview/components/plan-actions/plan-actions.tsx
- apps/frontend/src/pages/plan-style-overview/components/plan-actions/styles.module.css
- apps/frontend/src/pages/plan-style-overview/components/plan-style-category/styles.module.css
- apps/frontend/src/pages/plan-style-overview/styles.module.css
Tried to change styles to make buttons the same width for each viewport
Added grid to "My Plan" page when we have no plans yet
> fix(frontend): plan overview page buttons width difference cy-352

- apps/frontend/src/pages/home/components/visual-layouts/libs/constants.ts
**What was done?**
The constant layoutExamples, which serves as the data source for the section, was updated to contain only unique styles, eliminating the duplicate entries.
**Why was it done?**
This change addresses the issue described in the task 342, where the same three styles were repeated throughout the list, creating a poor visual impression.
For this update, I just removed the duplicate styles.
Removing the slider didn’t seem ideal, since it’s functional and can still be used to accommodate new styles in the future.
> fix: repeated styles in sample layouts cy-342

- apps/frontend/src/pages/auth/auth.tsx
Before Result:
- Input fields are cleared after error.
- Sign-Up errors redirect the user to Sign-In, losing all entered registration data.
Actual Result:
- Input values persist after an error is displayed (sing-in and sign-up pages).
- On Sign-Up, users only be redirected upon successful registration.
https://github.com/user-attachments/assets/6cf5c2fb-54f9-42eb-ad72-a4533a07da36
> fix(frontend): persist form input values after failed sign-in and sign-up cy-362

- apps/backend/src/modules/auth/auth.controller.ts
- apps/backend/src/modules/auth/auth.service.ts
- apps/backend/src/modules/plans/plans.ts
- apps/frontend/src/modules/auth/auth-api.ts
- apps/frontend/src/modules/auth/slices/actions.ts
Added logic to assign a user to a plan in the db after successful authentication.
- If a plan is generated while the user is not authenticated, the planId is saved in localStorage.
- When the user signs in or signs up, the userId is attached to the plan and the localStorage field is cleared.
- If someone manually changes the value in localStorage and the plan does not exist or belongs to another user, no changes are made and the localStorage field is cleared.
> fix: plan not associated to user after succesful authentication cy-349

- apps/backend/src/modules/users/helpers/user-validation.helper.ts
The problem was because logic operator OR was replaced with nullish coalescing operator which didn't accept falsy values.
I decided to adjust the normalizeField function, so that it accepts not only strings, but null values too. And we can apply it to the dob field. So now it works like this:
```
payload.dob = null -> normalizeField(null) -> updateData.dob = null
payload.dob = undefined -> it doesn't enter the scope of that block so we don't update that field at all
payload.dob = "" -> normalizeField("") -> updateData.dob = null
payload.dob = "2025-08-26" -> normalizeField("2025-08-26") -> updateData.dob = "2025-08-26"
```
> fix(backend): dob field doesn't accept nullish values cy-363

- apps/backend/src/modules/auth/auth.controller.ts
- apps/backend/src/modules/auth/auth.service.ts
- apps/backend/src/modules/auth/libs/types/types.ts
- apps/backend/src/modules/password-token/password-token.repository.ts
- apps/backend/src/modules/password-token/password-token.service.ts
- apps/backend/src/modules/users/libs/validation-schemas/validation-schemas.ts
- apps/backend/src/modules/users/users.ts
- apps/frontend/src/modules/auth/slices/actions.ts
- apps/frontend/src/pages/auth/components/reset-password/libs/constants/default-reset-password-values.ts
- apps/frontend/src/pages/auth/components/reset-password/reset-password.tsx
- packages/shared/src/index.ts
- packages/shared/src/modules/users/libs/enums/user-validation-message.enum.ts
- packages/shared/src/modules/users/libs/types/reset-password-request-dto.type.ts
- packages/shared/src/modules/users/libs/validation-schemas/forgot-password.validation-schema.ts
- packages/shared/src/modules/users/libs/validation-schemas/reset-password-with-token.validation-schema.ts
- packages/shared/src/modules/users/libs/validation-schemas/validation-schemas.ts
- packages/shared/src/modules/users/users.ts
Updated /auth/forgot-password logic:
- If user provides an incorrect email type (not a string), return 422 with message "This field requires a string value".
Updated  /auth/reset-password logic:
- Added validation for the backend payload.
- Included token in the payload.
Additional:
- Added deletion of password reset token in db once the reset link has been successfully used.
> fix: forgot/reset password endpoints – security and validation issues cy-385

- apps/frontend/src/libs/components/dashboard/components/greeting/styles.module.css
- apps/frontend/src/libs/components/dashboard/styles.module.css
Before Result:
- Icon inside the button overlaps with the button text.
- The wrapper does not cover the whole screen, leaving an empty gap at the bottom of the page.
Actual Result:
- "Create New Plan" button height and spacing remain consistent regardless of greeting length.
- Icon and text remain properly aligned.
- The wrapper cover the whole screen without leaving gaps or creating unecessary scrolling.
https://github.com/user-attachments/assets/9b4b1a06-f8b2-4298-a9f7-4566a7076f51
> fix(frontend): fix layout button and blank space at the bottom cy-398

- apps/frontend/src/pages/home/components/visual-layouts/styles.module.css
Before Result:
- User can't properly see the template. Around half is covered and can't be slided into view.
Actual Result:
https://github.com/user-attachments/assets/09c0e5c7-65a3-446e-ae45-d04cc4f641d9
> fix(frontend): fix slider of templates on mobile view cy-404

- apps/frontend/src/pages/plan-style-overview/plan-style-overview.tsx
https://github.com/user-attachments/assets/172b914d-3211-4476-a73a-b170c77b2693
> fix: Reload Plan-Style-Overview page breaks the app cy-418

- apps/frontend/src/pages/quiz/quiz.tsx
Fixed a bug that caused the progress of a previous quiz to be incorrectly loaded when trying to start a new quiz with a different category. 
The solution involved explicitly clearing the saved quiz state from the browser’s storage at the moment a new category is selected.
The bug occurred because the **“restart quiz”** logic, triggered when selecting a new category, only cleared the temporary application state (managed by Redux), but did not remove the state that was permanently stored in localStorage.
The fix ensures that the saved state is cleared whenever the user selects a new category.
Every time a user picks a category, the application first deletes any trace of a previous quiz from persistent storage and only then starts a completely new session.
> fix: quiz category issues cy-435

- apps/frontend/src/libs/components/plan-task-create-form/plan-task-create-form.tsx
- apps/frontend/src/libs/hooks/use-app-form/use-app-form.hook.ts
- apps/frontend/src/pages/dashboard-wrapper-mock/components/plan/plan.tsx
- apps/frontend/src/pages/home/components/feedbacks-section/components/feedback-modals/add-feedback.modal.tsx
- apps/frontend/src/pages/plan-edit/plan-edit.tsx
- apps/frontend/src/pages/plan-edit/styles.module.css
To support #431: 
- Added "manage plan" button on plan-edit page.
- Fixed "download" link on my-plan page.
- Fixed https://github.com/BinaryStudioAcademy/bsa-2025-checkly/issues/431#issuecomment-3237410015
> feat: add button to edit page cy-461
