apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
packages/shared/src/modules/users/libs/validation-schemas/user-sign-in.validation-schema.ts

- Changed input type in sign-in form
- Changed validation condition to apply the correct message

fix: Sign in cy-4

---

apps/backend/.env.example

Added example JWT values to `.env.example` for better clarity during setup.

docs: add example jwt configuration values to env example file cy-07

---

apps/frontend/src/assets/css/utilities/grid-pattern.css
apps/frontend/src/assets/css/variables/colors.css
apps/frontend/src/pages/auth/components/sign-up-form/sign-up-form.tsx
apps/frontend/src/pages/home/components/hero/styles.module.css
apps/frontend/src/pages/home/components/how-it-works/how-it-works.tsx
apps/frontend/src/pages/home/components/how-it-works/styles.module.css

Hello!
[Bug ticket link](https://github.com/orgs/BinaryStudioAcademy/projects/33/views/1?pane=issue&itemId=122361204&issue=BinaryStudioAcademy%7Cbsa-2025-checkly%7C107)
The list of changes:
1. Fixed Hero, How-it-works, and Sign-Up sections to replace img with DecorativeImage component to eliminate unwanted drag behavior.
2. Minor updates in How-it-works section:
- fixed text font-family
- updated mark-up to follow fluid practices

fix: dragged images cy-107

---

docs/test-strategy.md

Added bug report template and example. Fixed releaste date. Fixed minor grammar/spelling issues

docs: Update test strategy cy-118

---

apps/frontend/src/pages/home/components/categories/categories.tsx
apps/frontend/src/pages/home/components/categories/styles.module.css
apps/frontend/src/pages/home/home.tsx

Quick fix -  removed unnecessary code

fix: removed  placeholder text from home comp cy-156

---

apps/frontend/src/assets/css/variables/fluid-spacing.css
apps/frontend/src/libs/components/button/button.tsx
apps/frontend/src/pages/auth/components/shared/shared.module.css
apps/frontend/src/pages/auth/components/sign-in-form/libs/constants.ts
apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
apps/frontend/src/pages/auth/components/sign-in-form/styles.module.css
apps/frontend/src/pages/auth/components/sign-up-form/libs/constants.ts
apps/frontend/src/pages/auth/components/sign-up-form/sign-up-form.module.css
apps/frontend/src/pages/auth/components/sign-up-form/sign-up-form.tsx
apps/frontend/src/pages/auth/libs/constants.ts

Solution:
- Add more spacing around the form and adjust the car image positioning to ensure it doesn't touch or overlap the wrapper edges
- Make orange image bigger to improve the visual effect
- Replace wrong password input filed placeholder to match design pattern
https://github.com/user-attachments/assets/973facd5-2fdb-484e-b7a0-d43f8eff59eb

fix: remove sign-up white bar cy-164

---

apps/frontend/src/assets/css/reset.css
apps/frontend/src/assets/css/utilities/grid-pattern.css
apps/frontend/src/assets/css/variables/spacing.css
apps/frontend/src/pages/home/components/categories/categories.tsx
apps/frontend/src/pages/home/components/categories/category-item/category-item.tsx
apps/frontend/src/pages/home/components/categories/category-item/styles.module.css
apps/frontend/src/pages/home/components/categories/styles.module.css
apps/frontend/src/pages/home/components/feedbacks-section/components/feedback-decoration/feedbacksection-decoration.tsx
apps/frontend/src/pages/home/components/feedbacks-section/components/feedback-decoration/styles.module.css
apps/frontend/src/pages/home/components/feedbacks-section/feedbacks-section.tsx
apps/frontend/src/pages/home/components/feedbacks-section/styles.module.css
apps/frontend/src/pages/home/components/footer/styles.module.css
apps/frontend/src/pages/home/components/header/styles.module.css
apps/frontend/src/pages/home/components/hero/hero.tsx
apps/frontend/src/pages/home/components/hero/styles.module.css
apps/frontend/src/pages/home/components/how-it-works/how-it-works.tsx
apps/frontend/src/pages/home/components/how-it-works/styles.module.css
apps/frontend/src/pages/home/components/visual-layouts/styles.module.css
apps/frontend/src/pages/home/components/visual-layouts/visual-layouts.tsx

Hello,
[Bug #1 link](https://github.com/orgs/BinaryStudioAcademy/projects/33/views/1?pane=issue&itemId=123285165&issue=BinaryStudioAcademy%7Cbsa-2025-checkly%7C179)
[Bug #2 link](https://github.com/orgs/BinaryStudioAcademy/projects/33?pane=issue&itemId=123327845&issue=BinaryStudioAcademy%7Cbsa-2025-checkly%7C183)
Below is the list of fixes:
1. Repaired icon image animation on hover-in and hover-out.
2. Added missing background grid.
3. Optimized styles related to category-item and category section.
4. Fixed how-it-works section width issue.
5. Update all landing page sections to have common block paddings and spacings.
https://github.com/user-attachments/assets/86ebf64b-944c-4d1c-ae93-519d391111ae
https://github.com/user-attachments/assets/8ac1d644-2022-46e8-a02f-c8d35947d738

fix: category card animation cy-179

---

apps/frontend/src/libs/enums/enums.ts
apps/frontend/src/libs/enums/error-messages.enum.ts
apps/frontend/src/libs/helpers/get-error-message.ts
apps/frontend/src/libs/modules/store/listener-middleware/listener-middleware.ts
apps/frontend/src/modules/auth/slices/actions.ts

Fixed the toastify notification error to single message for sign-in to prevent leaking sensitive information

fix(frontend): fix toastify single error message sign-in cy-188

---

apps/frontend/src/pages/home/components/categories/category-item/category-item.tsx
apps/frontend/src/pages/home/components/feedbacks-section/components/user-avatar/user-avatar.tsx
apps/frontend/src/pages/home/components/visual-layouts/styles.module.css
apps/frontend/src/pages/home/components/visual-layouts/visual-layouts.tsx

Bug #211 
Bug #213 
1. Previous solution to bug #208 caused an animation issue when first element is hovered on.
2. Fixed images in landing page to replace img with the DecorativeImage component.
Issue:
https://github.com/user-attachments/assets/6317df71-6ca8-4f99-92d6-1b7b312fbab5
Solution:
https://github.com/user-attachments/assets/d6e8f68f-18bf-4213-abdd-18999d2875b9

fix: visual layouts animation + homepage draggable images cy-211

---

apps/frontend/src/assets/css/variables/layout.css
apps/frontend/src/assets/css/variables/spacing.css
apps/frontend/src/libs/components/app-header/styles.module.css
apps/frontend/src/libs/components/side-panel/styles.module.css

fix: Side Panel's border width is too big and uneven cy-234

---

apps/frontend/src/libs/components/app-header/app-header.tsx

fix: Header has incorrect background color and visible divider cy-235

---

apps/frontend/src/pages/dashboard-wrapper-mock/components/plan/components/day/styles.module.css

https://github.com/user-attachments/assets/94a97af7-5851-441d-880b-fa4b64a318e4

fix: make "day x" button container larger cy-333

---

apps/frontend/src/libs/constants/constants.ts
apps/frontend/src/libs/constants/plan-category.constants.tsx
apps/frontend/src/libs/types/plan-category-id.type.ts
apps/frontend/src/libs/types/types.ts
apps/frontend/src/pages/plan-style-overview/components/plan-actions/styles.module.css
apps/frontend/src/pages/plan-style-overview/components/plan-style-category/plan-style-category.tsx
apps/frontend/src/pages/plan-style-overview/components/plan-style-category/styles.module.css
apps/frontend/src/pages/plan-style-overview/plan-style-overview.tsx
apps/frontend/src/pages/plan-style-overview/styles.module.css

Before Result:
- Buttons at the top are too big.
- The "Login" text is below the buttons, and appears too large and too bold.
- Action buttons are being cutoff when stacking horizontally on some devices.
Actual Result:
- Format selection buttons use the same styles from 'Select Style' page.
- The "Login" text appear above the buttons and have less font weight.
- Action buttons switch direction earlier, to avoid being cutoff.
https://github.com/user-attachments/assets/13859427-cf90-4502-bf93-4ce9ea5e82b3

feat(frontend): improvement of responsive design for mobile cy-338

---

apps/frontend/src/pages/quiz/questions/components/question-navigation/question-navigation.tsx
apps/frontend/src/pages/quiz/quiz.tsx

Replaced Link to Button component and updated `ButtonVariant` for two quiz buttons.

fix: missing background on two quiz buttons cy-360

---

.hooks/prebuild/01_install_chromium_deps.sh

Added chromium dependency to the deployed server to be able to export a plan to pdf

fix: add chromium dep for plan export to pdf cy-0

---

apps/frontend/src/libs/enums/app-route.enum.ts
apps/frontend/src/pages/home/components/footer/footer.tsx
apps/frontend/src/pages/home/components/hero/hero.tsx
apps/frontend/src/pages/quiz/questions/components/notes-page/notes-page.tsx

feat: update landing links cy-380

---

apps/backend/src/modules/plans/plan.repository.ts
apps/frontend/src/pages/dashboard-wrapper-mock/components/plan/components/tasks/task/task.tsx

https://github.com/user-attachments/assets/7f637e80-ed92-4a73-9df1-b1521397016a

fix: manually edited tasks are not displayed cy-409

---

apps/frontend/src/pages/plan-style-overview/components/plan-actions/styles.module.css

Updated paddings for buttons and adjusted responsiveness.
https://github.com/user-attachments/assets/f001e922-61ba-481c-a37f-dd70cbd67691

fix: download button loader misaligned on plan overview cy-426

---

apps/backend/src/modules/tasks/task.controller.ts
apps/frontend/src/assets/img/icons/icons.tsx
apps/frontend/src/libs/components/components.ts
apps/frontend/src/libs/components/confirmation-modal/confirmation-modal.tsx
apps/frontend/src/libs/components/plan-task-create-form/libs/types/types.ts
apps/frontend/src/libs/components/plan-task-create-form/libs/validation-schemas/validation-schemas.ts
apps/frontend/src/libs/components/plan-task-create-form/plan-task-create-form.tsx
apps/frontend/src/libs/components/plan-task-create-form/plan-task-select-styles.ts
apps/frontend/src/libs/components/plan-task-create-form/styles.module.css
apps/frontend/src/libs/components/task-time-selector/libs/enums/enums.ts
apps/frontend/src/libs/components/task-time-selector/libs/types/types.ts
apps/frontend/src/libs/components/task-time-selector/task-time-selector.tsx
apps/frontend/src/libs/components/task-time-selector/time-time-select-styles.ts
apps/frontend/src/libs/hooks/use-app-form/use-app-form.hook.ts
apps/frontend/src/modules/tasks/libs/types/types.ts
apps/frontend/src/modules/tasks/slices/actions.ts
apps/frontend/src/modules/tasks/slices/task.ts
apps/frontend/src/modules/tasks/tasks-api.ts
apps/frontend/src/modules/tasks/tasks.ts
apps/frontend/src/pages/dashboard-wrapper-mock/components/plan/components/libs/types/types.ts
apps/frontend/src/pages/dashboard-wrapper-mock/components/plan/components/tasks/task/task.tsx
apps/frontend/src/pages/plan-edit/libs/types/types.ts
apps/frontend/src/pages/plan-edit/plan-edit.tsx
apps/frontend/src/pages/plan-edit/styles.module.css
packages/shared/src/index.ts
packages/shared/src/modules/tasks/libs/types/task-update-request-dto.type.ts
packages/shared/src/modules/tasks/libs/validation-schemas/task-create.validation-schema.ts
packages/shared/src/modules/tasks/libs/validation-schemas/validation-schemas.ts
packages/shared/src/modules/tasks/tasks.ts

Hello!
Here's the list of changes (ref #431):
- Added "Time of Day Editing" feature.
- User can add personal tasks on the plan-edit page.
- Updated "my plan" dashboard page to add "Time of Day Editing" feature.
- Updated description to Regenerate Modals.
https://github.com/user-attachments/assets/b31b0ccf-1e7d-4f4f-80b1-b426f6cde96d
https://github.com/user-attachments/assets/2f092a1f-7cba-46ca-9c94-c491eb66a287

feat: plan edit page inhancements cy-431

---

apps/frontend/src/modules/auth/slices/actions.ts
apps/frontend/src/modules/plans/slices/actions.ts
apps/frontend/src/modules/plans/slices/plan.slice.ts
apps/frontend/src/pages/choose-style/choose-style.tsx

- Fixed the chosen style is not applied immediately
- Keep selected style after page reload

fix: Selected plan style enhancement cy-472

---

apps/frontend/src/libs/components/modal/modal.tsx
apps/frontend/src/libs/components/modal/styles.module.css
apps/frontend/src/pages/dashboard-wrapper-mock/components/plan/components/tasks/list/list.tsx
apps/frontend/src/pages/dashboard-wrapper-mock/components/plan/plan.tsx
apps/frontend/src/pages/home/components/categories/categories.tsx
apps/frontend/src/pages/home/components/categories/styles.module.css
apps/frontend/src/pages/plan-edit/libs/types/render-task-input-properties.type.ts
apps/frontend/src/pages/plan-edit/plan-edit.tsx

Trying to fix this issue https://github.com/BinaryStudioAcademy/bsa-2025-checkly/issues/454#issuecomment-3238141050

fix: update task adding and task deletion cy-485
